name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use a valid Node.js version (e.g., 14.x.x)

      - name: Install UglifyJS and GzipJS
        run: |
          npm install uglify-js -g
          npm install gzip-js -g

      - name: Create Dist Directory
        run: mkdir -p ./dist   # Create a directory to store minimized files

      - name: Minify and Uglify JS files
        run: |
          for file in ./*.js; do
            base=$(basename "$file" .js)
            npx uglify-js "$file" -o "./dist/$base.min.js" --compress --mangle
          done
        working-directory: ${{ github.workspace }}

      - name: Gzip JS files
        run: |
          for file in ./dist/*.min.js; do
            gzip -c "$file" > "$file.gz"
          done
        working-directory: ${{ github.workspace }}

      - name: Verify Output Files
        run: |
          ls -al ./dist
        working-directory: ${{ github.workspace }}
